#!/bin/bash
# Docker镜像构建脚本 - 适用于Linux环境
# 修改后支持电脑端宽度的markdown-to-image-serve

set -e

echo "🐳 开始构建 markdown-to-image-serve Docker镜像..."
echo "📋 修改内容："
echo "  - 默认宽度从1200x1600改为1920x1080"
echo "  - 支持自定义width和height参数"
echo "  - 海报内容宽度优化为电脑端显示"
echo ""

# 检查Docker是否可用
if ! command -v docker &> /dev/null; then
    echo "❌ Docker未找到，请先安装Docker"
    echo ""
    echo "🔗 安装链接："
    echo "  macOS: https://docs.docker.com/desktop/install/mac-install/"
    echo "  Windows: https://docs.docker.com/desktop/install/windows-install/"
    echo "  Linux: https://docs.docker.com/engine/install/"
    exit 1
fi

# 获取版本信息
VERSION=${1:-"desktop-width-$(date +%Y%m%d)"}
IMAGE_NAME="markdown-to-image-serve"
FULL_TAG="${IMAGE_NAME}:${VERSION}"

echo "🏷️  镜像标签: ${FULL_TAG}"
echo ""

# 构建多平台镜像
echo "🔨 构建Docker镜像..."
docker buildx create --use --name multiarch-builder 2>/dev/null || true
docker buildx build \
    --platform linux/amd64,linux/arm64 \
    --tag "${FULL_TAG}" \
    --tag "${IMAGE_NAME}:latest" \
    --load \
    .

echo ""
echo "✅ 构建完成!"
echo ""
echo "📋 使用方法："
echo "  docker run -d -p 3000:3000 ${FULL_TAG}"
echo ""
echo "🌐 访问地址："
echo "  http://localhost:3000"
echo ""
echo "📚 API调用示例："
echo '  curl -X POST http://localhost:3000/api/generatePosterImage \'
echo '    -H "Content-Type: application/json" \'
echo '    -d "{'
echo '      \"markdown\": \"# 测试\\n\\n这是一个电脑端宽度的测试\",'
echo '      \"header\": \"测试报告\",'
echo '      \"footer\": \"Generated by desktop-width version\",'
echo '      \"theme\": \"SpringGradientWave\",'
echo '      \"width\": 1200,'
echo '      \"height\": 800'
echo '    }"'
echo ""
echo "🔧 导出镜像（可选）："
echo "  docker save ${FULL_TAG} > ${IMAGE_NAME}-${VERSION}.tar"
echo ""
echo "📦 加载镜像（在其他机器上）："
echo "  docker load < ${IMAGE_NAME}-${VERSION}.tar"
