version: '0.1'

services:
  app:
    # 使用本地构建
    # build:
      # context: .
    # 使用已有的远程镜像
    image: wxingheng/markdown-to-image-serve:0.0.1
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - CHROME_PATH=/usr/bin/google-chrome-unstable
      - API_PASSWORD=your_secure_password_here
    volumes:
      - .:/app
      - /app/node_modules
      # 指定缓存目录, 避免每次重新构建
      - /app/.next 
      # 需要将容器中的文件挂载到宿主机
      - ./public/uploads/posters:/tmp/uploads/posters
