version: '0.1'

services:
  app:
    build:
      context: .
    # 指定平台 amd64 架构 （Mac Apple Silicon 平台）
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - CHROME_PATH=/usr/bin/google-chrome-unstable
    volumes:
      - .:/app
      - /app/node_modules
      # 指定缓存目录, 避免每次重新构建
      - /app/.next 
      # 需要将容器中的文件挂载到宿主机
      - ./public/uploads/posters:/tmp/uploads/posters
