#!/bin/bash
# API 测试脚本 - 演示自定义宽度和密码校验功能

set -e

API_URL="http://localhost:3000/api/generatePosterImage"
API_PASSWORD="your_secure_password_here"

echo "🧪 测试 Markdown to Image API"
echo "================================"
echo ""

# 测试1: 基础功能测试
echo "📋 测试1: 基础功能 (默认尺寸)"
RESPONSE1=$(curl -s -X POST "${API_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "markdown": "# 基础测试\n\n这是一个基础功能测试，使用默认尺寸。\n\n## 功能特点\n- 支持 Markdown 格式\n- 自动生成图片\n- 美观的主题",
    "header": "基础功能测试",
    "footer": "Generated by API Test",
    "theme": "SpringGradientWave",
    "password": "'"${API_PASSWORD}"'"
  }')

echo "响应: $RESPONSE1"
echo ""

# 测试2: 自定义宽度测试
echo "📋 测试2: 自定义宽度 (1600x900)"
RESPONSE2=$(curl -s -X POST "${API_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "markdown": "# 宽屏测试\n\n这是一个自定义宽度测试，使用 1600x900 尺寸。\n\n## 宽屏优势\n- 更多内容展示空间\n- 适合电脑端显示\n- 高清图片质量\n\n### 数据表格\n| 项目 | 数值 | 备注 |\n|------|------|------|\n| 宽度 | 1600px | 自定义 |\n| 高度 | 900px | 自定义 |\n| 质量 | 高清 | 优秀 |",
    "header": "宽屏尺寸测试",
    "footer": "1600x900 自定义尺寸",
    "theme": "blue",
    "width": 1600,
    "height": 900,
    "password": "'"${API_PASSWORD}"'"
  }')

echo "响应: $RESPONSE2"
echo ""

# 测试3: 竖屏尺寸测试
echo "📋 测试3: 竖屏尺寸 (800x1200)"
RESPONSE3=$(curl -s -X POST "${API_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "markdown": "# 竖屏测试\n\n这是一个竖屏尺寸测试，适合移动端显示。\n\n## 移动端优化\n- 竖屏布局\n- 适合手机显示\n- 内容紧凑排列\n\n### 特色功能\n1. **自适应布局**\n2. **高清渲染**\n3. **快速生成**\n\n> 完美适配移动设备！",
    "header": "竖屏尺寸测试",
    "footer": "800x1200 移动端尺寸",
    "theme": "purple",
    "width": 800,
    "height": 1200,
    "password": "'"${API_PASSWORD}"'"
  }')

echo "响应: $RESPONSE3"
echo ""

# 测试4: 错误测试 - 无密码
echo "📋 测试4: 密码校验测试 (应该失败)"
RESPONSE4=$(curl -s -X POST "${API_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "markdown": "# 无密码测试\n\n这个请求应该会失败，因为没有提供密码。",
    "header": "无密码测试"
  }')

echo "响应: $RESPONSE4"
echo ""

# 测试5: 错误测试 - 错误密码
echo "📋 测试5: 错误密码测试 (应该失败)"
RESPONSE5=$(curl -s -X POST "${API_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "markdown": "# 错误密码测试\n\n这个请求应该会失败，因为密码不正确。",
    "header": "错误密码测试",
    "password": "wrong_password"
  }')

echo "响应: $RESPONSE5"
echo ""

# 测试6: 边界值测试
echo "📋 测试6: 边界值测试 (最大尺寸)"
RESPONSE6=$(curl -s -X POST "${API_URL}" \
  -H "Content-Type: application/json" \
  -d '{
    "markdown": "# 最大尺寸测试\n\n这是一个最大尺寸测试，使用 3840x2160 (4K) 尺寸。\n\n## 4K 特点\n- 超高清分辨率\n- 细节丰富\n- 专业品质\n\n### 应用场景\n- 大屏显示\n- 打印输出\n- 专业设计\n\n**注意**: 生成时间可能较长，请耐心等待。",
    "header": "4K 超高清测试",
    "footer": "3840x2160 4K分辨率",
    "theme": "green",
    "width": 3840,
    "height": 2160,
    "password": "'"${API_PASSWORD}"'"
  }')

echo "响应: $RESPONSE6"
echo ""

echo "✅ 所有测试完成！"
echo ""
echo "🎯 测试总结："
echo "  - 基础功能: 默认尺寸生成"
echo "  - 自定义宽度: 1600x900 宽屏"
echo "  - 竖屏尺寸: 800x1200 移动端"
echo "  - 密码校验: 无密码/错误密码应该失败"
echo "  - 边界测试: 3840x2160 4K分辨率"
echo ""
echo "📁 生成的图片文件保存在: public/uploads/posters/"
echo "🌐 可通过浏览器访问: http://localhost:3000/uploads/posters/"
