name: Docker Build and Push (Simple)

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t wxingheng/markdown-to-image-serve:${{ env.VERSION }} .
        docker build -t wxingheng/markdown-to-image-serve:latest .

    - name: Push Docker image
      run: |
        docker push wxingheng/markdown-to-image-serve:${{ env.VERSION }}
        docker push wxingheng/markdown-to-image-serve:latest

    - name: Verify push
      run: |
        echo "✅ Successfully pushed version ${{ env.VERSION }} and latest" 